POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json

{
    "name": "Product 3",
    "price": 1.25
}

###

GET http://localhost:8080/products/d999a5af-0f7f-4330-84f4-c05e149fc4f9 HTTP/1.1
Content-Type: application/json