POST http://localhost:8080/products HTTP/1.1
Content-Type: application/json

{
    "name": "Product 10",
    "price": 1.25
}

###

GET http://localhost:8080/products/4d0036b9-3571-4ea9-bb59-a0dc95d23221 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:8080/products?page=1&limit=3 HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8080/products/4d0036b9-3571-4ea9-bb59-a0dc95d23221 HTTP/1.1
Content-Type: application/json

{
    "name": "Product 1 - Updated Again",
    "price": 5.00
}

###

DELETE http://localhost:8080/products/4d0036b9-3571-4ea9-bb59-a0dc95d23221 HTTP/1.1
Content-Type: application/json

