POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "Name": "Alefe",
    "Email": "a@a.com",
    "Password": "aaaa"
}


###

POST http://localhost:8080/users/get_token HTTP/1.1
Content-Type: application/json

{
    "Email": "a@a.com",
    "Password": "aaaa"
}